# -*- coding: utf-8 -*-
"""Q1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsACSuK5af54fE90p1yaHnVVvKoL1kVf
"""

weight = float(input("Enter weight in kg: "))
height = float(input("Enter height in meters: "))

bmi = weight / (height * height)

print("BMI:", bmi)