# -*- coding: utf-8 -*-
"""Q10

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsACSuK5af54fE90p1yaHnVVvKoL1kVf
"""

numbers = []
n = int(input("How many numbers do you want to enter? "))

for i in range(n):
    val = float(input("Enter number: "))
    numbers.append(val)

largest = numbers[0]
for num in numbers:
    if num > largest:
        largest = num

print("Largest number:", largest)