# -*- coding: utf-8 -*-
"""Q12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsACSuK5af54fE90p1yaHnVVvKoL1kVf
"""

squares = {}

for i in range(1, 16):
    squares[i] = i * i

print(squares)