# -*- coding: utf-8 -*-
"""Q5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsACSuK5af54fE90p1yaHnVVvKoL1kVf
"""

numbers = []
n = int(input("How many numbers do you want to enter? "))

for i in range(n):
    val = float(input("Enter number: "))
    numbers.append(val)

limit = float(input("Enter threshold number: "))

filtered_numbers = []
for num in numbers:
    if num >= limit:
        filtered_numbers.append(num)

print("Filtered list:", filtered_numbers)