# -*- coding: utf-8 -*-
"""Q7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsACSuK5af54fE90p1yaHnVVvKoL1kVf
"""

word = input("Enter a word: ")
reversed_word = ""

for char in word:
    reversed_word = char + reversed_word

print("Reversed word:", reversed_word)