# -*- coding: utf-8 -*-
"""Q9

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsACSuK5af54fE90p1yaHnVVvKoL1kVf
"""

num = int(input("Input a number: "))

for i in range(1, 11):
    print(num, "x", i, "=", num * i)